### ISSUE TITLE
Remove the node_modules from the repo

### ISSUE THREAD

**Issue by nfauchelle** [cey0030/URL-Shortener-Microservice#1]
Hi,

You should add the node_modules file to your projects .gitignore file.

Once added you can use `git rm -r --cached node_modules ` to remove the folder from git while still keeping it on your computer.

**Comment by cey0030** [comment]
Thanks for the comment, I'll do that 

Is the reason for ignoring node_modules because it contains important info? Or is it just best practice? I'm fairly new to Node
