### ISSUE TITLE
Database credentials have been comitted

### ISSUE THREAD

**Issue by nfauchelle** [cey0030/URL-Shortener-Microservice#2]
https://github.com/cey0030/URL-Shortener-Microservice/blob/master/server.js#L18

These should be in environment files / config files that are not added to the repo.

Hopefully this is just a single use password and not used anywhere else (PayPal / email?) otherwise you better change it.

**Comment by cey0030** [comment]
Hi Nick,

Thanks for bringing this to my attention! 

Luckily that DB is just for practice and isn't linked to anything important, but I'll hide the project so that I can make the changes you suggested
